In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('mtcars.csv')
df.head(2)

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0      Mazda RX4  21.0    6  160.0  110   3.9  2.620  16.46   0   1     4   
1  Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4   

   carb  
0     4  
1     4

### ___Missing Data___

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   model   32 non-null     object 
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64  
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64  
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64  
 9   am      32 non-null     int64  
 10  gear    32 non-null     int64  
 11  carb    32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [7]:
df.iloc[0:5,0:5][[False,True,False,False,True]] # shows columns that has been marked as true in the list provided

model   mpg  cyl   disp   hp
1      Mazda RX4 Wag  21.0    6  160.0  110
4  Hornet Sportabout  18.7    8  360.0  175

In [8]:
df.hp > 100

0      True
1      True
2     False
3      True
4      True
5      True
6      True
7     False
8     False
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17    False
18    False
19    False
20    False
21     True
22     True
23     True
24     True
25    False
26    False
27     True
28     True
29     True
30     True
31     True
Name: hp, dtype: bool

In [10]:
df[df.mpg > 25] # only shows columns that are marked as true for the given expression

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
17        Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4   
18     Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4   
19  Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4   
25       Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4   
26   Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5   
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5   

    carb  
17     1  
18     2  
19     1  
25     1  
26     2  
27     2

In [14]:
df[df.mpg < 20].shape[0]

18

In [15]:
df[df.mpg < 20]

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   

    gear  carb  
4      3     2  
5      3     1  
6      3     4  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
28     5     4  
29     5     6  
30     5     8

In [19]:
df[(df.mpg >20) & (df.hp > 110)]

model   mpg  cyl  disp   hp  drat     wt  qsec  vs  am  gear  carb
27  Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.9   1   1     5     2

In [23]:
# transmission is automatic and milage > 20
df [ (df.am == 1) & (df.mpg > 20)] # always use bitwise & operator and not "and" operator

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0        Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1    Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2       Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
17        Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4   
18     Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4   
19  Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4   
25       Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4   
26   Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5   
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4   

    carb  
0      4  
1      4  
2      1  
17     1  
18     2  
19     1  
25     1  
26     2  
27     2  
31     2

In [26]:
# hp > 40 and mpg > 18 and am == 1
df[ (df.hp > 140) & (df.mpg > 18) & (df.am == 1) ]

model   mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
29  Ferrari Dino  19.7    6  145.0  175  3.62  2.77  15.5   0   1     5     6

# __SORTING THE DATAFRAME__

In [58]:
df.sort_values('cyl', ascending=True, kind='mergesort', na_position='first')

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   

    gear  carb  
2      4     1  
7      4     2  
8      4     2  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
25     4     1  
26     5     2  
27     5     2  
31     4     2  
0      4     4  
1      4     4  
3      3     1  
5      3     1  
9      4     4  
10     4     4  
29     5     6  
4      3     2  
6      3     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
28     5     4  
30     5     8

In [62]:
# you can see above that the index is jumbled as it moved with the record while ordering the data or sorting
# if one wants to ignore this you can use ignore_index kwarg
df.sort_values('cyl', ascending=True, kind='mergesort', na_position='first', ignore_index=True)

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
1             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
2              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
3              Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
4           Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
5        Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
6         Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
7             Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
8         Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
9          Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
10           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   
11            Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
12        Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
13       Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
14              Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
15             Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
16            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
17         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
18    Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
19           Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
20           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
21           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
22          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
23   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
24  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
25    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
26     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
27          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
28           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
29     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
30       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
31        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   

    gear  carb  
0      4     1  
1      4     2  
2      4     2  
3      4     1  
4      4     2  
5      4     1  
6      3     1  
7      4     1  
8      5     2  
9      5     2  
10     4     2  
11     4     4  
12     4     4  
13     3     1  
14     3     1  
15     4     4  
16     4     4  
17     5     6  
18     3     2  
19     3     4  
20     3     3  
21     3     3  
22     3     3  
23     3     4  
24     3     4  
25     3     4  
26     3     2  
27     3     2  
28     3     4  
29     3     2  
30     5     4  
31     5     8

In [64]:
# sorting using more than one column
df.sort_values(['model','mpg','hp'])

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
22     3     2  
14     3     4  
23     3     4  
16     3     4  
2      4     1  
21     3     2  
6      3     4  
29     5     6  
17     4     1  
25     4     1  
28     5     4  
18     4     2  
3      3     1  
4      3     2  
15     3     4  
27     5     2  
30     5     8  
0      4     4  
1      4     4  
8      4     2  
7      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
24     3     2  
26     5     2  
19     4     1  
20     3     1  
5      3     1  
31     4     2

In [65]:
# sort with more than one column where one column should be in ascending and other in descending
df.sort_values(['mpg','hp'], ascending=[True, False])

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   

    gear  carb  
15     3     4  
14     3     4  
23     3     4  
6      3     4  
16     3     4  
30     5     8  
13     3     3  
22     3     2  
21     3     2  
28     5     4  
11     3     3  
12     3     3  
10     4     4  
5      3     1  
4      3     2  
24     3     2  
9      4     4  
29     5     6  
0      4     4  
1      4     4  
3      3     1  
31     4     2  
20     3     1  
8      4     2  
2      4     1  
7      4     2  
26     5     2  
25     4     1  
27     5     2  
18     4     2  
17     4     1  
19     4     1

# __UNIQUE__

In [66]:
df.head(10)

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
5            Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
6         Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
7          Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
8           Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
9           Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2  
5     1  
6     4  
7     2  
8     2  
9     4

In [67]:
# how many unique values are there in a column e.g am
df.am.unique()

array([1, 0])

In [68]:
df.gear.unique()

array([4, 3, 5])

In [69]:
df.carb.unique()

array([4, 1, 2, 3, 6, 8])

In [70]:
df.gear.value_counts()

3    15
4    12
5     5
Name: gear, dtype: int64

In [71]:
df.am.value_counts()

0    19
1    13
Name: am, dtype: int64

In [72]:
df.cyl.unique()

array([6, 4, 8])

In [73]:
df.cyl.value_counts()

8    14
4    11
6     7
Name: cyl, dtype: int64

In [75]:
df.cyl.values

array([6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8, 8, 8, 4, 4, 4, 4, 8,
       8, 8, 8, 4, 4, 4, 8, 6, 8, 4])

In [76]:
# how many cars have automatic and manual transmission
df.am.value_counts()

0    19
1    13
Name: am, dtype: int64

In [77]:
# 19 cars are manual and 13 cars are automatic(am)