# Numpy
### NUMerical PYthon

Numpy is a python package that has numerical applications and its a good starter package to perform Linear algebric calculations. It uses arrays to create matrix and vectors.

1. Numpy works on array of elements
2. Numpy arrays are homogeneous

__Datatypes:__

* float64
* int64
* U32 - string

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1.2,3.4,5.6,7.8,9.0])
arr1.dtype

dtype('float64')

In [4]:
arr2 = np.array([1,2,3,4.5,6])
arr2.dtype

dtype('float64')

In [5]:
arr2.size

5

In [6]:
len(arr2)

5

In [8]:
# create a 2 dim array
arr_2dim = np.array([[1,2],[3,4],[5,6]])
arr_2dim

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
# create a 3 dimensional array
arr_3dim = np.array([ [[1,2,3],[2,3,4],[4,5,6]],[[2,3,4],[4,5,6],[6,7,8]],[[8,9,8],[3,4,5],[3,4,6]] ])
arr_3dim

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]],

       [[2, 3, 4],
        [4, 5, 6],
        [6, 7, 8]],

       [[8, 9, 8],
        [3, 4, 5],
        [3, 4, 6]]])

In [12]:
arr_3dim.dtype

dtype('int64')

In [13]:
arr_3dim.ndim

3

In [22]:
# 4 dim array
arr_4dim = np.array([ [[[2,3],[4,5]],[[3,7],[4,7]]],[[[8,6],[9,3]],[[20,10],[11,4]]] ])
arr_4dim

array([[[[ 2,  3],
         [ 4,  5]],

        [[ 3,  7],
         [ 4,  7]]],


       [[[ 8,  6],
         [ 9,  3]],

        [[20, 10],
         [11,  4]]]])

In [23]:
arr_4dim.ndim

4

In [24]:
arr_4dim.shape

(2, 2, 2, 2)

In [25]:
arr_4dim[0].shape

(2, 2, 2)

In [26]:
len(arr_4dim)

2

In [27]:
arr_4dim[1].shape

(2, 2, 2)

#### Numpy arange - used to return n number of elements in a single dimension array

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr_r = np.arange(1,25)

In [21]:
arr_r.reshape((2,3,4))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [24]:
np.arange(100).reshape(4,5,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [25]:
# create a numpy array of shape 8,7
np.arange(56).reshape(8,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55]])

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
# create a np array of shape 80 10 2 2 and should be all zeros
arr19 = np.zeros(3200).reshape(80,10,2,2)

In [31]:
arr20 = np.arange(10)

In [32]:
arr20.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
arr20.reshape(5, -1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

When you put -1 as an argument for any reshape method besides other argument numpy automatically detects which multiple is suitable if any for that particular argument and returns the shape of array accordingly as in the above example we have given 5, -1 as an argument so numpy automatically identifies that 2 is the correct argument for this shape

In [35]:
arr19.reshape(100,-1,-1)

ValueError: can only specify one unknown dimension

run the code above and you will see an error which means only one unknown dimension (represented as -1) can be specified while calling reshape method

In [36]:
arr19.reshape(100,2,-1)

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

__Convert any n dimensional array to 1 dim array using reshape(-1) or ravel()__

In [37]:
arr_re = np.arange(10).reshape(5,2)

In [38]:
arr_re.shape

(5, 2)

In [39]:
arr_re.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr_re.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.random.randint(0,11,10)

array([0, 9, 5, 3, 1, 6, 7, 2, 2, 3])

In [42]:
np.random.rand()

0.24639265188875192

In [47]:
np.random.randint(0,10,5) #np.random.randint(start, end, number of random elements)

array([1, 1, 8, 6, 1])

# Floor and Ceil

In [48]:
arr22 = np.array([1.22, 3.14, 6.20, 5.88, 9.22])

In [50]:
np.floor(arr22)

array([1., 3., 6., 5., 9.])

In [51]:
np.ceil(arr22)

array([ 2.,  4.,  7.,  6., 10.])

# ___Stacking___

In [52]:
arr23 = np.arange(10).reshape(2,5)

In [53]:
arr24 = np.arange(20).reshape(4,5)

In [56]:
np.vstack((arr23,arr24))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
np.hstack((arr23, arr24))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

In [58]:
arr25 = np.arange(9).reshape(3,3)
arr225a = np.arange(9).reshape(3,3)

In [60]:
np.vstack((arr25,arr225a))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
np.hstack((arr25, arr225a))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

### Typecasting using astype() method

In [75]:
np.hstack((arr25,arr225a)).astype('cdouble')

array([[0.+0.j, 1.+0.j, 2.+0.j, 0.+0.j, 1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j, 5.+0.j, 3.+0.j, 4.+0.j, 5.+0.j],
       [6.+0.j, 7.+0.j, 8.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

# ___Split___

In [76]:
# Split divides the array into multiple parts

In [77]:
arr28 = np.hstack((arr25, arr225a))
arr29 = np.vstack((arr25, arr225a))

In [82]:
np.vsplit(arr28,3)

[array([[0, 1, 2, 0, 1, 2]]),
 array([[3, 4, 5, 3, 4, 5]]),
 array([[6, 7, 8, 6, 7, 8]])]

In [87]:
np.vsplit(arr29,6)

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]])]

In [88]:
np.hsplit(arr29,3)

[array([[0],
        [3],
        [6],
        [0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7],
        [1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8],
        [2],
        [5],
        [8]])]

In [89]:
np.vsplit(arr28,3)

[array([[0, 1, 2, 0, 1, 2]]),
 array([[3, 4, 5, 3, 4, 5]]),
 array([[6, 7, 8, 6, 7, 8]])]

In [90]:
# create a numpy array of shape 20, 10 and divide it into 2 equal parts horizontally

In [93]:
arr30 = np.arange(200).reshape(20,10)

In [94]:
arr30

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [92]:
np.hsplit(arr30,2)

[array([[  0,   1,   2,   3,   4],
        [ 10,  11,  12,  13,  14],
        [ 20,  21,  22,  23,  24],
        [ 30,  31,  32,  33,  34],
        [ 40,  41,  42,  43,  44],
        [ 50,  51,  52,  53,  54],
        [ 60,  61,  62,  63,  64],
        [ 70,  71,  72,  73,  74],
        [ 80,  81,  82,  83,  84],
        [ 90,  91,  92,  93,  94],
        [100, 101, 102, 103, 104],
        [110, 111, 112, 113, 114],
        [120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144],
        [150, 151, 152, 153, 154],
        [160, 161, 162, 163, 164],
        [170, 171, 172, 173, 174],
        [180, 181, 182, 183, 184],
        [190, 191, 192, 193, 194]]),
 array([[  5,   6,   7,   8,   9],
        [ 15,  16,  17,  18,  19],
        [ 25,  26,  27,  28,  29],
        [ 35,  36,  37,  38,  39],
        [ 45,  46,  47,  48,  49],
        [ 55,  56,  57,  58,  59],
        [ 65,  66,  67,  68,  69],
        [ 75,  76,  77,  78,  79],
        [ 85,  86,

In [95]:
np.vsplit(arr30,5)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]]),
 array([[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]),
 array([[120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159]]),
 array([[160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
        [170, 171, 172, 173, 174, 175, 176, 177, 178

In [96]:
arr31, arr32 = np.hsplit(np.arange(200).reshape(20,10), 2)

In [97]:
arr31

array([[  0,   1,   2,   3,   4],
       [ 10,  11,  12,  13,  14],
       [ 20,  21,  22,  23,  24],
       [ 30,  31,  32,  33,  34],
       [ 40,  41,  42,  43,  44],
       [ 50,  51,  52,  53,  54],
       [ 60,  61,  62,  63,  64],
       [ 70,  71,  72,  73,  74],
       [ 80,  81,  82,  83,  84],
       [ 90,  91,  92,  93,  94],
       [100, 101, 102, 103, 104],
       [110, 111, 112, 113, 114],
       [120, 121, 122, 123, 124],
       [130, 131, 132, 133, 134],
       [140, 141, 142, 143, 144],
       [150, 151, 152, 153, 154],
       [160, 161, 162, 163, 164],
       [170, 171, 172, 173, 174],
       [180, 181, 182, 183, 184],
       [190, 191, 192, 193, 194]])

In [98]:
arr32

array([[  5,   6,   7,   8,   9],
       [ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28,  29],
       [ 35,  36,  37,  38,  39],
       [ 45,  46,  47,  48,  49],
       [ 55,  56,  57,  58,  59],
       [ 65,  66,  67,  68,  69],
       [ 75,  76,  77,  78,  79],
       [ 85,  86,  87,  88,  89],
       [ 95,  96,  97,  98,  99],
       [105, 106, 107, 108, 109],
       [115, 116, 117, 118, 119],
       [125, 126, 127, 128, 129],
       [135, 136, 137, 138, 139],
       [145, 146, 147, 148, 149],
       [155, 156, 157, 158, 159],
       [165, 166, 167, 168, 169],
       [175, 176, 177, 178, 179],
       [185, 186, 187, 188, 189],
       [195, 196, 197, 198, 199]])

In [99]:
arr33, arr34, arr35, arr36, arr37 = np.vsplit(np.arange(200).reshape(20,10), 5)

In [100]:
arr33

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [101]:
arr34

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [102]:
arr35

array([[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [103]:
arr36

array([[120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159]])

In [104]:
arr37

array([[160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])